package com.nirbhayram.org.accessingdatamysql.controller;


import com.nirbhayram.org.accessingdatamysql.entity.UserRepository;
import com.nirbhayram.org.accessingdatamysql.entity.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestBody User user) {
    userRepository.save(user);
    return "{'message':'user created'}";
  }

  @GetMapping(path="/user/{id}")
  public @ResponseBody User getUserById(@PathVariable int id){
    Optional<User> optional = userRepository.findById(id);
    if (!optional.isEmpty()){
      return optional.get();
    }
    return null;
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
}