package com.nirbhayram.org.accessingdatamysql.controller;


import com.nirbhayram.org.accessingdatamysql.entity.user.User;
import com.nirbhayram.org.accessingdatamysql.service.user.IUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class UserController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private IUserService userService;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestBody User user) {
    userService.addUser(user);
    return "{'message':'user created'}";
  }

  @GetMapping(path="/user/{id}")
  public @ResponseBody User getUserById(@PathVariable int id){
    User user = userService.getUserById(id);
    if (null==user){
      return null;
    }
    return user;
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userService.getAllUser();
  }
}